# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

strategy:
  matrix:
    linux_node_10:
      imageName: Hosted Ubuntu 1604
      node_version: 10.x
    linux_node_12:
      imageName: Hosted Ubuntu 1604
      node_version: 12.x
    mac_node_10:
      imageName: Hosted macOS
      node_version: 10.x
    mac_node_12:
      imageName: Hosted macOS
      node_version: 12.x
    windows_node_10:
      imageName: Hosted VS2017
      node_version: 10.x
    windows_node_12:
      imageName: Hosted VS2017
      node_version: 12.x

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
  env:
    DISPLAY: ':99.0'

- bash: |
    npm install
    npm run compile
  displayName: Build
  env:
    DISPLAY: ':99.0'

- bash: |
    npm run test
  displayName: Run Tests
  env:
    DISPLAY: ':99.0'